### ISSUE TITLE
[Test result] Your plugin works fine!

### ISSUE THREAD

**Issue by dpa99c** [cloakedninjas/cordova-plugin-backup#1]
Just to let you know I've tested your plugin in a test Cordova app with `cordova-android@6.3.0` on a Nexus 6P running Android 8.1 and the backup/restore works properly across multiple backup/restore operations.

However, I found I did need to manually invoke the backup manager (as instructed in [the documentation](http://androiddoc.qiniudn.com/training/backup/autosyncapi.html#testing)) to force backing up of the updated values:

    // call backup() in the app with updated values

    $ adb shell bmgr run

    $ adb shell bmgr fullbackup <PACKAGE>

    // re-install the app and call restore() to get the updated values

I plan to extend your plugin since Android 6+ supports autobackup so the manual backup service will not be needed (but it's still need for 5.1 and below) and for iOS using iCloud backup.

Thanks for your implementation and honesty regarding issues when testing.

**Comment by cloakedninjas** [comment]
Yeah, I got a response on that SO post and the issue was that I was getting rate-limited. I'll update the readme and remove the warning.

Thanks for testing it

**Comment by dpa99c** [comment]
I've published my plugin in which the Android manual backup for Android 5 and below is based on yours so thanks: https://github.com/dpa99c/cordova-plugin-cloud-settings
